### PR TITLE
Make all clipboard events composed by default.

### PR DESCRIPTION
**Pull request by TakayoshiKochi**
This resolves https://github.com/w3c/clipboard-apis/issues/61

### CODE REVIEW

**Comment by TakayoshiKochi** [comment]
Please hold on reviewing until #61 concludes.

**Comment by garykac** [comment]
Can you make these edits to the `index.bs` file instead of the HTML file?
The .HTML file is auto-generated from the .BS file, so they'll be overwritten if we edit the HTML file directly.

**Comment by TakayoshiKochi** [comment]
Done.  Could you take another look?

**Comment by foolip** [comment]
Hi all,

This quarter @rakuco and I have been looking into a [normative spec change without tests](https://docs.google.com/document/d/1kFYTqUMEbo9p87i6wAzORoicMWgHsuYwL2CgtvdhDaE/edit#heading=h.gn90gr74sg9s) to help us understand how [testing in standards](https://github.com/foolip/testing-in-standards) is working out in practice, and where there's more infrastructure work needed to make it practical.

This week I ended up here, and I think https://github.com/w3c/clipboard-apis/pull/58 and https://github.com/w3c/clipboard-apis/commit/11619a7 (no PR?) might also be testable, but less obviously so.

It looks like there weren't any tests for any events at all in https://github.com/w3c/web-platform-tests/tree/master/clipboard-apis, presumably because they'd have to be manual. To convince myself it's possible, I wrote a manual test that exercises this change:
https://github.com/w3c/web-platform-tests/pull/9626 (review appreciated)

Question for everyone here: what automation bits would you need in https://w3c.github.io/webdriver/webdriver-spec.html and exposed in http://web-platform-tests.org/writing-tests/testdriver.html to be able to reliably test changes to this spec? If you could file an issue on the web-platform-tests repo and add the type:untestable label, that'd be much appreciated.

In the meantime, do you think that writing manual tests is worthwhile? Is there any useful advice that should go in https://github.com/w3c/clipboard-apis/blob/master/CONTRIBUTING.md#tests?

**Comment by TakayoshiKochi** [comment]
Thanks @foolip for catching this.

As you imagined, this needs a manual test (could be automated by test driver?) and I was thinking of writing some tests while I'm changing the implementation in Blink - and you went ahead of me :)

I thought we can do document.execCommand('copy'), but turned out using execCommand() is not reliable :(

**Comment by TakayoshiKochi** [comment]
FYI, this is my wip CL
https://chromium-review.googlesource.com/c/chromium/src/+/923671

**Comment by foolip** [comment]
@kereliuk, do you have an update on testdriver.js support for keyboard input? I think that could be used to copy-paste, although it'd assume something about the key combinations that do it on various platforms. With that these tests should be possible to automate.

My follow-up question is whether it is generally true that changes in the Clipboard API spec get tests from implementations shortly thereafter? In that case it seems like a very good place to be. But I wonder how often things fall through the cracks, so that spec changes are made but no implementer ever follows, and it takes years before anyone notices?

**Comment by kereliuk** [comment]
Working on the keyboard input/direct WebDriver now, should have a PR up soon.

There has been discussion about adding some sort of spec support for clipboard stuff in WebDriver like copy and paste and not just have it as using the keyboard, (notably at TPAC last year). But not much of a consensus was reached and it becomes tricky if we want to use the system clipboard especially in the case where there are multiple sessions running at the same time which is common.

**Comment by foolip** [comment]
I guess we could put copy/paste/cut with keyboard in testdriver.js and implement using WebDriver, so that it can be overridden on platforms where the keyboard shortcuts aren't the same.

We really can't get around the fact that the clipboard is global I think, at most we could try to warn about it somewhere.

**Pull request merged**
