### PR TITLE
Pull request for Issue #40

### PR DESCRIPTION
**Pull request by gked**
This change updates wording in Algorithms section (6) to accurately reflect on what should actually happen to target selection in non-edtiable
contexts.
https://github.com/w3c/clipboard-apis/issues/40

### CODE REVIEW

**Comment by garykac** [comment]
@gked Have you resolved your IPR issues to contribute?

**Comment by gked** [comment]
I linked my GitHub account with w3c account. It should be working now

**Comment by garykac** [comment]
Thanks for fixing the IPR issue. Can you sync and re-bikeshed to resolve the conflicts?

**Comment by gked** [comment]
Apologies for not getting back to you. I can see that you've merged the changes already.

**Pull request merged**
