### PR TITLE
Emphasize visability in the "pick target"-algorithm

### PR DESCRIPTION
**Pull request by hugoholgersson**
This change addresses the ambiguity of unfocused and hidden
selections (#57) by stating that only a visible selection can be a
ClipboardEvent-target.

### CODE REVIEW

**Comment by hugoholgersson** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by garykac** [comment]
Sorry for taking so long to get around to this. Can you make these edits to the `index.bs` file instead of the HTML file?
The .HTML file is auto-generated from the .BS file, so they'll be overwritten if we edit the HTML file directly.
(I've updated the readme.md file to note that contributions should be made to the .BS file -- it wasn't clear before).

**Comment by hugoholgersson** [comment]
I've moved the changes to `index.bs`. PTAL. Please merge the changes if everything's all right.

**Comment by garykac** [comment]
LGTM, although the fact that both part of the "if content is editable" are the same is actually a bug that I introduced when converting the spec.
I'll merge this and then re-add the IF along with the correct ELSE clause.

**Pull request merged**
