### PR TITLE
Add SVG format to the spec.

### LINKED ISSUE #92: Make it possible to read image/svg+xml from the clipboard
I get the impression here https://w3c.github.io/clipboard-apis/#reading-from-clipboard that the clipboard format image/svg+xml should be available when reading a data transfer object in the paste event. But I cannot get this to work.
I have verified on Windows that there is indeed an image/svg+xml format on the clipboard, but I cannot see any traces of this when inspecting the clipboardData object in Chrome 75.0.3770.100. Have I misunderstood how this is supposed to work or is it simply not implemented in Chrome?

document.addEventListener('paste', async function (event) {
  event.preventDefault();
  console.log(event.clipboardData.types);
  let clipText = event.clipboardData.getData("image/svg+xml");
console.log(clipText);
}

### PR DESCRIPTION
**Pull request by snianu**
Closes #92 

For normative changes, the following tasks have been completed:

 * [ ] Modified Web platform tests (link to pull request)

Implementation commitment:

 * [X] WebKit (https://lists.webkit.org/pipermail/webkit-dev/2021-August/031940.html)
 * [X] Chromium (https://bugs.chromium.org/p/chromium/issues/detail?id=1110511)
 * [X] Gecko (https://github.com/mozilla/standards-positions/issues/549)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/216.html" title="Last updated on Jun 3, 2024, 5:58 PM UTC (dc0142d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/216/c858eb2...dc0142d.html" title="Last updated on Jun 3, 2024, 5:58 PM UTC (dc0142d)">Diff</a>

### CODE REVIEW

**Review by sanketj — APPROVED** [review]
LGTM

**Comment by snianu** [comment]
@EdgarChen Gentle ping..

**Review by EdgarChen — APPROVED** [review]
Looks good to me.

**Comment by annevk** [comment]
This doesn't seem to define any of the sanitization required...

**Pull request merged**
