### PR TITLE
Update group

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/pull/151.html" title="Last updated on Aug 6, 2021, 7:53 PM UTC (2d263c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/clipboard-apis/151/ee2d998...2d263c4.html" title="Last updated on Aug 6, 2021, 7:53 PM UTC (2d263c4)">Diff</a>

### CODE REVIEW

**Comment by annevk** [comment]
That's a separate WG?

**Comment by marcoscaceres** [comment]
>That's a separate WG?

Yep, no longer part of WebAppsWG.

**Review by travisleithead — APPROVED** [review]
Much appreciated!

**Comment by travisleithead** [comment]
Of course this means a bikeshed update... Filed https://github.com/tabatkins/bikeshed/issues/2122 to track that.

**Pull request merged**
